spring.application.name=lms-backend

server.port=${PORT:9292}

# PostgreSQL (Supabase Connection Pooler - IPv4 Compatible)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:5432/postgres?sslmode=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres.oogyunpfbvlqxlsqwuwm}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Sakib72542Sakib}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# JWT Security Configuration
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt.expiration-ms=86400000

# Springdoc OpenAPI Swagger Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Spring Mail SMTP Configuration (Gmail / Mailtrap / Custom SMTP)
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:sakibshourov440@gmail.com}
spring.mail.password=${MAIL_PASSWORD:otit yqbg mrsp dlcg}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true